### PR TITLE
Include dat://scott.ee to user pages category

### PR DESCRIPTION
**Pull request by scottsweb**
Adding my personal site to the new explore section.

### CODE REVIEW

**Comment by todrobbins** [comment]
Now seeding 🌱

**Comment by scottsweb** [comment]
Thanks @todrobbins, right back at you :smile: 

This reminds me that I would like to find a way to seed a number of sites at the same time using the CLI. Haven't worked that out yet so I rely on beaker for managing multiple seeds.

**Comment by pfrazee** [comment]
👍 Merged and published!

**Comment by scottsweb** [comment]
Much appreciated, thank you :bowing_man:

**Pull request merged**
